l_english:
  newsfeed_subject_self_label: "Me"
  newsfeed_subject_self_icon: "@newsfeed_icon_self!"
  newsfeed_subject_spouse_label: "My [spouse|E]"
  newsfeed_subject_spouse_icon: "@newsfeed_icon_spouse!"
  newsfeed_subject_close_dynastic_family_label: "[close_family|E] of my [dynasty|E]"
  newsfeed_subject_close_dynastic_family_icon: "@newsfeed_icon_close_dynastic_family!"
  newsfeed_subject_extended_dynastic_family_label: "[extended_family|E] of my [dynasty|E]"
  newsfeed_subject_extended_dynastic_family_icon: "@newsfeed_icon_extended_dynastic_family!"
  newsfeed_subject_liege_label: "My [liege|E]"
  newsfeed_subject_liege_icon: "@newsfeed_icon_liege!"
  newsfeed_subject_direct_vassal_label: "My direct [vassals|E]"
  newsfeed_subject_direct_vassal_icon: "@newsfeed_icon_direct_vassal!"
  newsfeed_subject_pinned_character_label: "My pinned characters"
  newsfeed_subject_pinned_character_icon: "@newsfeed_icon_pinned_character!"

  newsfeed_type_marriage_label: "Marriages"
  newsfeed_type_pregnancy_label: "Pregnancies"
  newsfeed_type_birth_label: "Births"
  newsfeed_type_death_label: "Deaths"
  newsfeed_type_war_label: "Wars"
  newsfeed_type_titles_label: "Titles"